version: '3.1'

services:
  db:
    image: mariadb:10.6
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    depends_on:
      - db

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: notSecureChangeMe